---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: myapp-tls-secret
  namespace: my-web-app
spec:
  encryptedData:
    tls.crt: AgBoHRw1iFNMql0WSWf9OlPe+QiQLJRbu90Q3iyCspvvhTaUOCTgYGb/uoawrQW5tSMcxUKyW6qFhnCsRGFIWH5XoAMnP+rzZgQL3OzngPDU6HBnhUlnDZvNxLITKqlJKQR+B/M+fSvpwW0w3bOFbKra5qx12CfifH4b7N7mEHYOv8esgPqfI7CVY/kMa5WYEEAOFd6xB1tlepnRX+WG9I1vUnO0mvdsV8WZYrg2T2HkaITVdOt/Nc/0W/X8ya8ae8yhc3Xu20rTUi1AphQ+/UN2fQFyh99sJVQc+z6lupATNzld1x+AkDAhSZhYlMc+ykC+BQxGMfgYtBy7rLq3MgI+QtmGd43tE/1jIpXcT9vc/k1wDzo/sVFNBZtJmRV3HWUAqLthlJNSBXr8tzggu4ezj+4BwRgxi29qucQOltmJ/dgXJJVPXgNpgDqFGLfdHxXAvYq3WEmfQp5PLVgnFMKoj2Dnwp1umTB0ks6uheHsxsYc8B7JSIZxgiQy48JnHX9iJthUMU7qc/5tKLnKmnyCx+RREUn1ekeYXS9MivxXz8ZXVq4hAs78xjUWsxEV+JOgpSPwI10MdhR8O4YqGTieXqoglCuQ9YidIqoRzOvL68DgtKe9UzFBw0fWVxKis3TSmhmGzQAJReiMjLeCPK+/P+Gp8aFCggAJLq97mNh5M1SZKyTwC3yEXyKfS/8LPIw=
    tls.key: AgCqoYGiMaY8jivD+Zc+cGM+586fwmBlNbemynl9lgVdUMyyLHT/D/gkrphaoaW3Kfhx/QJ5Pg3EVrSrsbkh6dCE65x2MNT97HdSng9qyJwo2wfuf7x8XPogHC/VkPuIlBRyxhqIkZI+q1KyGTZ6N4c612iPZBVCqwWh735WHpq8PqzFg3z1kD8mhsxknbSrBsc2m6tSSNcQlbCvA83iTCvOUnPLaEiqr7WwYM4JWgnDsxebnu+z5u27wTHPuB8d4HyNtmVYOESKHc62Br14KOk2VqUB7d92baE2JwL0OB9f2Cq59589iyh56+Mjjt9Iwq5PyJW/r3IhR7kuBnhCEqGr/fxtZxx65nNJ9l8th91yUtxpfrBkJy66d7W4nQVAftVxBvEeGIAbJz1vK5eiDSAq1C8m4gy5EWzNEMuTBf9DiMFaZymc4aKKKSBR7KQiLxRbV6TFR1SyemoC5DB14FHRqVDgiMlLBaXaC8vJ9mpng7SygXOPDJtnAoDEUmDAkYOJ6tIZuk1vrdQi7CvmO3NzYLa4oGSSZxj8f0jKTKxgJsF6pnzVZC4RDhETO+CqTsrJGbjJ7c2gGIV3iNeQ5fmENdQrNn1lWuoKQGHd9+j/ZUD7xPWiyLvmNf7easU9krSi1t30TYz6xHdPz9nKi1ZiSuH8hmZ6HF30UDWPW6qMaTFnPyYBKGOAB9ADsPHXjrE=
  template:
    metadata:
      creationTimestamp: null
      name: myapp-tls-secret
      namespace: my-web-app
    type: kubernetes.io/tls
