apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-depends-ingress
  namespace: my-web-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - myapp.local
    secretName: myapp-tls-secret
  rules:
  - host: myapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: it-depends-service
            port:
              number: 80